### ISSUE TITLE
META - site rework

### ISSUE THREAD

**Issue by JdeGuise** [JdeGuise/johndeguise.com#56]
- [ ] update .pdf resume
- [ ] redesign front page
- [ ] stuff resume behind /resume endpoint
- [ ] create new logo for site
